//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyShopDataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvImage
    {
        public AdvImage()
        {
            this.Order = 0;
            this.Versions = new HashSet<AdvImageVersion>();
        }
    
        public int Id { get; set; }
        public int Order { get; set; }
    
        public virtual ProductImage ProductImage { get; set; }
        public virtual Adv24au Adv24au { get; set; }
        public virtual ICollection<AdvImageVersion> Versions { get; set; }
        public virtual AdvImageVersion CurrentVersion { get; set; }
    }
}
