//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyShopDataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvImageVersion
    {
        public AdvImageVersion()
        {
            this.Data = "";
        }
    
        public int Id { get; set; }
        public string Data { get; set; }
    
        public virtual ProductImageVersion ProductImageVersion { get; set; }
        public virtual AdvImage AdvImage { get; set; }
    }
}
