//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyShopDataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class BegemotSale
    {
        public BegemotSale()
        {
            this.BegemotSalePrice = new HashSet<BegemotSalePrice>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateStop { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<BegemotSalePrice> BegemotSalePrice { get; set; }
    }
}
