//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyShopDataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marketplace
    {
        public Marketplace()
        {
            this.Active = true;
            this.Styles = new HashSet<Style>();
            this.Advs = new HashSet<Adv24au>();
            this.AdvCategory = new HashSet<AdvCategory>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public bool Active { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Style> Styles { get; set; }
        public virtual ICollection<Adv24au> Advs { get; set; }
        public virtual ICollection<AdvCategory> AdvCategory { get; set; }
    }
}
