//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyShopDataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ImgPricePosition = 0;
            this.Advs = new HashSet<Adv24au>();
            this.SpecialStyle = new HashSet<Style>();
            this.Sales = new HashSet<Sale>();
            this.Images = new HashSet<ProductImage>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public decimal PriceOld { get; set; }
        public string Article { get; set; }
        public bool Active { get; set; }
        public int ImgPricePosition { get; set; }
        public Nullable<decimal> BRetailPrice { get; set; }
        public Nullable<decimal> BWholeSalePrice { get; set; }
        public Nullable<int> BCount { get; set; }
    
        public virtual ICollection<Adv24au> Advs { get; set; }
        public virtual ICollection<Style> SpecialStyle { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual ProductCategory Category { get; set; }
        public virtual ICollection<ProductImage> Images { get; set; }
        public virtual BegemotProduct BegemotProduct { get; set; }
    }
}
