//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyShopDataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public ProductImage()
        {
            this.Order = 0;
            this.UseSource = false;
            this.IsNoImage = false;
            this.PricePosition = 0;
            this.Versions = new HashSet<ProductImageVersion>();
            this.AdvImages = new HashSet<AdvImage>();
        }
    
        public int Id { get; set; }
        public int Order { get; set; }
        public string SourcePath { get; set; }
        public bool UseSource { get; set; }
        public bool IsNoImage { get; set; }
        public int PricePosition { get; set; }
    
        public virtual ICollection<ProductImageVersion> Versions { get; set; }
        public virtual ProductImageVersion CurrentVersion { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<AdvImage> AdvImages { get; set; }
    }
}
