//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyShopDataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImageVersion
    {
        public ProductImageVersion()
        {
            this.Style = 0;
            this.AdvImageVersions = new HashSet<AdvImageVersion>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public decimal PriceNew { get; set; }
        public decimal PriceOld { get; set; }
        public string Path { get; set; }
        public int Style { get; set; }
    
        public virtual ProductImage ProductImage { get; set; }
        public virtual ICollection<AdvImageVersion> AdvImageVersions { get; set; }
    }
}
