//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyShopDataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public Sale()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateExpire { get; set; }
        public string Algoritm { get; set; }
        public System.DateTime DateUpdate { get; set; }
        public bool Active { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string MarginMin { get; set; }
        public string MarginMax { get; set; }
        public string MarginToWholesale { get; set; }
        public string DescountToRetail { get; set; }
        public bool UseMaxResult { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual Style Style { get; set; }
    }
}
