//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyShopDataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Style
    {
        public Style()
        {
            this.Products = new HashSet<Product>();
            this.Sales = new HashSet<Sale>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Header { get; set; }
        public string Content { get; set; }
        public string Footer { get; set; }
        public int ShowCaseStyle { get; set; }
        public int Type { get; set; }
        public System.DateTime DateUpdate { get; set; }
        public bool Active { get; set; }
        public string Name { get; set; }
        public int DefMrkCategory { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual Marketplace Marketplace { get; set; }
    }
}
