//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyShopDataLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ToyShopModelContainer : DbContext
    {
        public ToyShopModelContainer()
            : base("name=ToyShopModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BegemotProduct> BegemotProductSet { get; set; }
        public DbSet<BegemotPriceHistory> BegemotPriceHistorySet { get; set; }
        public DbSet<BegemotCountHistory> BegemotCountHistorySet { get; set; }
        public DbSet<BegemotSale> BegemotSaleSet { get; set; }
        public DbSet<BegemotSalePrice> BegemotSalePriceSet { get; set; }
        public DbSet<Product> ProductSet { get; set; }
        public DbSet<Adv24au> Adv24auSet { get; set; }
        public DbSet<Style> StyleSet { get; set; }
        public DbSet<Sale> SaleSet { get; set; }
        public DbSet<Marketplace> MarketplaceSet { get; set; }
        public DbSet<ProductCategory> ProductCategorySet { get; set; }
        public DbSet<AdvCategory> AdvCategorySet { get; set; }
        public DbSet<ProductImage> ProductImageSet { get; set; }
        public DbSet<ProductImageVersion> ProductImageVersionSet { get; set; }
        public DbSet<AdvImageVersion> AdvImageVersionSet { get; set; }
        public DbSet<AdvImage> AdvImageSet { get; set; }
    }
}
