//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.UriOnSupplier = "";
        }
    
        public int Id { get; set; }
        public string UriOnSupplier { get; set; }
        public string LocalPath { get; set; }
        public int StatusCode { get; set; }
        public Nullable<int> IdOnWebStore { get; set; }
    
        public virtual SupplierProduct SupplierProduct { get; set; }
        public virtual SupplierCategory SupplierCategory { get; set; }
        public virtual ShopCategory ShopCategory { get; set; }
        public virtual ShopProduct ShopProduct { get; set; }
        public virtual SupplierProduct SupplierProductAsDefault { get; set; }
        public virtual ShopProduct ShopProductDefault { get; set; }
        public virtual ShopCategory ShopCategoryDefault { get; set; }
    }
}
