//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopCategory
    {
        public ShopCategory()
        {
            this.InShop = false;
            this.Description = "";
            this.Products = new HashSet<ShopProduct>();
            this.Images = new HashSet<Image>();
            this.Childs = new HashSet<ShopCategory>();
            this.SupplierCategories = new HashSet<SupplierCategory>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public bool InShop { get; set; }
        public Nullable<int> IdOnWebStore { get; set; }
        public string Description { get; set; }
        public string LinkRewrite { get; set; }
    
        public virtual ICollection<ShopProduct> Products { get; set; }
        public virtual ICollection<Image> Images { get; set; }
        public virtual ICollection<ShopCategory> Childs { get; set; }
        public virtual ShopCategory Parent { get; set; }
        public virtual ICollection<SupplierCategory> SupplierCategories { get; set; }
        public virtual Image DefaultImage { get; set; }
    }
}
