//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDataLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopEntities : DbContext
    {
        public ShopEntities()
            : base("name=ShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SupplierProduct> SupplierProductSet { get; set; }
        public DbSet<Supplier> SupplierSet { get; set; }
        public DbSet<SupplierCategory> SupplierCategorySet { get; set; }
        public DbSet<ShopProduct> ShopProductSet { get; set; }
        public DbSet<ShopCategory> ShopCategorySet { get; set; }
        public DbSet<Image> ImageSet { get; set; }
        public DbSet<PropertyHystory> PropertyHystorySet { get; set; }
        public DbSet<Settings> SettingsSet { get; set; }
    }
}
