//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopProduct
    {
        public ShopProduct()
        {
            this.ShortDescription = "";
            this.InShop = false;
            this.Unity = "";
            this.LinkRewrite = "";
            this.SupplierProducts = new HashSet<SupplierProduct>();
            this.Images = new HashSet<Image>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public decimal Price { get; set; }
        public decimal DiscountPrice { get; set; }
        public bool IsSale { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public bool InShop { get; set; }
        public Nullable<int> IdOnWebStore { get; set; }
        public string Unity { get; set; }
        public string LinkRewrite { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual ShopCategory Category { get; set; }
        public virtual ICollection<SupplierProduct> SupplierProducts { get; set; }
        public virtual ICollection<Image> Images { get; set; }
        public virtual Image DefaultImage { get; set; }
    }
}
