//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierProduct
    {
        public SupplierProduct()
        {
            this.Images = new HashSet<Image>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string IdOnSource { get; set; }
        public string UriOnSource { get; set; }
        public decimal DiscountPrice { get; set; }
        public decimal Price { get; set; }
        public bool IsSale { get; set; }
        public string Description { get; set; }
        public decimal CostPrice { get; set; }
        public int StatusCode { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual ShopProduct ShopProduct { get; set; }
        public virtual ICollection<Image> Images { get; set; }
        public virtual SupplierCategory Category { get; set; }
        public virtual Image DefaultImage { get; set; }
    }
}
