//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.Products = new HashSet<SupplierProduct>();
            this.Categories = new HashSet<SupplierCategory>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Uri { get; set; }
        public decimal Discount { get; set; }
    
        public virtual ICollection<SupplierProduct> Products { get; set; }
        public virtual ICollection<SupplierCategory> Categories { get; set; }
    }
}
