//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierCategory
    {
        public SupplierCategory()
        {
            this.IdOnSource = "";
            this.UriOnSource = "";
            this.SupplierImage = new HashSet<Image>();
            this.Childs = new HashSet<SupplierCategory>();
            this.Products = new HashSet<SupplierProduct>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string IdOnSource { get; set; }
        public string UriOnSource { get; set; }
        public int StatusCode { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<Image> SupplierImage { get; set; }
        public virtual ICollection<SupplierCategory> Childs { get; set; }
        public virtual SupplierCategory Parent { get; set; }
        public virtual ICollection<SupplierProduct> Products { get; set; }
        public virtual ShopCategory ShopCategory { get; set; }
    }
}
